"""Rebuild the paper's two LIVE figures on probe-v3 traces (2026-08-20).

Bug this fixes: `live_dualview.json` / `latency_profile.json` were
generated by modal_stream.py::live_dualview off `gated_traces_v2.parquet`
— that file is the streaming-loop-v2 / probe-**v1** sweep (2026-07-30).
The probe v2 (8u) and v3 (8z-live) re-runs wrote frozen_v{2,3}_traces
and only the external-bench figures were refreshed, so fig:live and
fig:pareto in the paper still showed v1 arms (.400/.446/.529/.633 at
0/14/35/55%) while RESULTS quoted v3 (.383/.483/.554/.596 at 0/16/35/61%).

Recomputes both JSONs from frozen_v3_traces.parquet (+ eval_expert gold)
with the same schema and the same paired-bootstrap recipe, archives the
v1 files as *_v1.json, and redraws live_dualview in the house style.
pareto_latency.py then picks the refreshed numbers up unchanged.

Run from figures/: ..\\..\\.venv_ip\\Scripts\\python live_v3_figures.py
"""
import json
import os
import shutil

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

BLUE, GREEN = "#2a78d6", "#1baf7a"
INK, MUT, GRID = "#0b0b0b", "#52514e", "#e6e4de"
ARMS = ("never", "conservative", "balanced", "aggressive", "always")
DATA = "../data"
N_BOOT, SEED = 10000, 42

old = json.load(open("live_dualview.json"))
for f in ("live_dualview.json", "latency_profile.json"):
    if not os.path.exists(f.replace(".json", "_v1.json")):
        shutil.copy(f, f.replace(".json", "_v1.json"))
for f in ("live_dualview.png", "pareto_latency.png", "pareto_latency.pdf"):
    if os.path.exists(f) and not os.path.exists(
            f.replace(".", "_v1.", 1)):
        shutil.copy(f, f.replace(".", "_v1.", 1))

df = pd.read_parquet(f"{DATA}/frozen_v3_traces.parquet")
df = df[df["tier"].isin(ARMS) & df["heard_ok"].notna()]
heard = df.pivot(index="id", columns="tier", values="heard_ok").dropna()
esc = (df.pivot(index="id", columns="tier", values="mode")
       .loc[heard.index] == "escalated")

exp = pd.read_parquet(f"{DATA}/eval_expert.parquet").set_index("id")
b = lambda x: 1 if x is True or x == 1 else 0
gold = np.array([b(exp["expert_adequate"].get(i)) for i in heard.index])

A = heard[list(ARMS)].to_numpy(float)
E = esc[list(ARMS)].to_numpy(bool)
B = np.where(E, gold[:, None], A)
n = len(heard)
rates, hm, gm = E.mean(axis=0), A.mean(axis=0), B.mean(axis=0)
ceil = float(gold.mean())

rng = np.random.default_rng(SEED)
idx = rng.integers(0, n, size=(N_BOOT, n))
ciA = np.percentile(A[idx].mean(axis=1), [2.5, 97.5], axis=0)
ciB = np.percentile(B[idx].mean(axis=1), [2.5, 97.5], axis=0)
ciC = np.percentile(gold[idx].mean(axis=1), [2.5, 97.5])

json.dump({"n": n, "n_boot": N_BOOT,
           "offline_floor": old.get("offline_floor"),
           "gold_big": ceil, "gold_big_ci": ciC.tolist(),
           "probe": "v3",
           "source": "frozen_v3_traces.parquet",
           "arms": {a: {"esc": float(rates[j]), "heard": float(hm[j]),
                        "heard_ci": [float(ciA[0, j]), float(ciA[1, j])],
                        "gold_inject": float(gm[j]),
                        "gold_inject_ci": [float(ciB[0, j]),
                                           float(ciB[1, j])]}
                    for j, a in enumerate(ARMS)}},
          open("live_dualview.json", "w"), indent=1)

# ---- latency profile, same schema ---------------------------------------
df["expert_ms"] = df["expert_latency_s"].fillna(0) * 1000
is_esc = df["mode"] == "escalated"
df["total_ms"] = np.where(
    is_esc,
    df["eot_read_ms"] + np.maximum(df["stall_ms"].fillna(0),
                                   df["expert_ms"]) + df["relay_ms"].fillna(0),
    df["eot_read_ms"] + df["answer_ms"].fillna(0))
dfc = df[df["id"].isin(heard.index)]


def stats(s):
    s = s.dropna() / 1000
    if not len(s):
        return None
    return {"n": int(len(s)), "mean": round(float(s.mean()), 2),
            "p50": round(float(s.median()), 2),
            "p95": round(float(s.quantile(.95)), 2),
            "p99": round(float(s.quantile(.99)), 2)}


prof, never_all = {}, None
for a in ARMS:
    sub = dfc[dfc["tier"] == a]
    row = {"all": stats(sub["total_ms"]),
           "local": stats(sub[sub["mode"] != "escalated"]["total_ms"]),
           "escalated": stats(sub[sub["mode"] == "escalated"]["total_ms"])}
    if a == "never":
        never_all = row["all"]
    else:
        row["delta_vs_never"] = {
            k: round(row["all"][k] - never_all[k], 2)
            for k in ("mean", "p50", "p95", "p99")}
    prof[a] = row
old_lat = json.load(open("latency_profile_v1.json"))
json.dump({"component": old_lat.get("component"), "probe": "v3",
           "source": "frozen_v3_traces.parquet", "arm": prof},
          open("latency_profile.json", "w"), indent=1)

# ---- dual-view figure ----------------------------------------------------
fig, ax = plt.subplots(figsize=(6.4, 4.2))
xr = np.array([0, 1])
ax.plot(xr, [hm[0] + (ceil - hm[0]) * r for r in xr], ls="--", lw=1.0,
        color=MUT, alpha=.8, zorder=2,
        label="random escalation (pairs with the gold view)")
ax.axhline(ceil, color=GREEN, ls=":", lw=1.2, alpha=.75, zorder=1)
ax.text(.02, ceil + .012, f"always-escalate (gpt-5.5 on gold text) "
        f"{ceil:.3f}", fontsize=7.5, color=GREEN)
ax.errorbar(rates, gm, yerr=[gm - ciB[0], ciB[1] - gm], fmt="--s", ms=5.5,
            color=GREEN, capsize=3, lw=1.4, alpha=.9, zorder=3,
            label="gold-inject — counterfactual: expert answers the gold text")
ax.errorbar(rates, hm, yerr=[hm - ciA[0], ciA[1] - hm], fmt="-o", ms=6,
            color=BLUE, capsize=3, lw=1.7, zorder=4,
            label="heard-acc — deployed: expert answers the talker's transcript")
for j, a in enumerate(ARMS):
    ax.annotate(f"{a}\n{rates[j]:.0%}", (rates[j], hm[j]), xytext=(5, -20),
                textcoords="offset points", fontsize=7.5, color=BLUE)
ax.annotate("", xy=(rates[3], gm[3] - .012), xytext=(rates[3], hm[3] + .012),
            arrowprops=dict(arrowstyle="<->", color=MUT, lw=.9))
ax.text(rates[3] - .03, (hm[3] + gm[3]) / 2,
        f"speech-channel cost\n−{gm[3] - hm[3]:.3f}", fontsize=7.5,
        color=MUT, va="center", ha="right")
ax.set_xlabel("realized escalation rate", fontsize=9)
ax.set_ylabel(f"accuracy on the live test set (n={n})", fontsize=9)
ax.set_title("The live gate, two views — frozen 600-query pool\n"
             "probe v3, per-domain quantile thresholds; our "
             "reference-anchored judge", fontsize=9.5, loc="left")
ax.set_xlim(-.03, 1.03)
ax.set_ylim(.30, 1.0)
ax.grid(color=GRID, lw=.7, zorder=0)
for s in ("top", "right"):
    ax.spines[s].set_visible(False)
ax.tick_params(labelsize=8)
h, l = ax.get_legend_handles_labels()
ax.legend(h[::-1], l[::-1], loc="lower right", fontsize=7.5, frameon=False)
fig.tight_layout()
for ext in ("png", "pdf"):
    fig.savefig(f"live_dualview.{ext}", dpi=220, bbox_inches="tight")
plt.close(fig)

print(f"n={n} esc={np.round(rates, 3)}")
print(f"heard v1 .400/.446/.529/.633  ->  v3 {np.round(hm, 3)}")
print(f"gold  v1 .400/.500/.637/.767  ->  v3 {np.round(gm, 3)}")
print(f"ceiling {ceil:.3f} | P50 "
      f"{[prof[a]['all']['p50'] for a in ARMS]} | P99 "
      f"{[prof[a]['all']['p99'] for a in ARMS]}")
print("wrote live_dualview.{json,png,pdf} + latency_profile.json "
      "(v1 archived as *_v1)")
